export function toolSoftwareLinux() {
  return [
    {
      text: 'linux命令概述',
      items: [
        { text: 'cat命令', link: '/toolSoftware/Linux/' },
        { text: 'aspell命令', link: '/toolSoftware/Linux/aspell命令' },
        { text: 'awk命令', link: '/toolSoftware/Linux/awk命令' },
        { text: 'chattr命令', link: '/toolSoftware/Linux/chattr命令' },
        { text: 'chmod命令', link: '/toolSoftware/Linux/chmod命令' },
        { text: 'chown命令', link: '/toolSoftware/Linux/chown命令' },
        { text: 'cmp命令', link: '/toolSoftware/Linux/cmp命令' },
        { text: 'col命令', link: '/toolSoftware/Linux/col命令' },
        { text: 'colrm命令', link: '/toolSoftware/Linux/colrm命令' },
        { text: 'comm命令', link: '/toolSoftware/Linux/comm命令' },
        { text: 'csplit命令', link: '/toolSoftware/Linux/csplit命令' },
        { text: 'curl命令', link: '/toolSoftware/Linux/curl命令' },
        { text: 'cut命令', link: '/toolSoftware/Linux/cut命令' },
        { text: 'diff命令', link: '/toolSoftware/Linux/diff命令' },
        { text: 'diffstat命令', link: '/toolSoftware/Linux/diffstat命令' },
        { text: 'ed命令', link: '/toolSoftware/Linux/ed命令' },
        { text: 'egrep命令', link: '/toolSoftware/Linux/egrep命令' },
        { text: 'ex命令', link: '/toolSoftware/Linux/ex命令' },
        { text: 'expr命令', link: '/toolSoftware/Linux/expr命令' },
        { text: 'fgrep命令', link: '/toolSoftware/Linux/fgrep命令' },
        { text: 'file命令', link: '/toolSoftware/Linux/file命令' },
        { text: 'find命令', link: '/toolSoftware/Linux/find命令' },
        { text: 'fmt命令', link: '/toolSoftware/Linux/fmt命令' },
        { text: 'fold命令', link: '/toolSoftware/Linux/fold命令' },
        { text: 'grep命令', link: '/toolSoftware/Linux/grep命令' },
        { text: 'ip命令', link: '/toolSoftware/Linux/ip命令' },
        { text: 'join命令', link: '/toolSoftware/Linux/join命令' },
        { text: 'journalctl命令', link: '/toolSoftware/Linux/journalctl命令' },
        { text: 'less命令', link: '/toolSoftware/Linux/less命令' },
        { text: 'ln命令', link: '/toolSoftware/Linux/ln命令' },
        { text: 'locate命令', link: '/toolSoftware/Linux/locate命令' },
        { text: 'look命令', link: '/toolSoftware/Linux/look命令' },
        { text: 'lsattr命令', link: '/toolSoftware/Linux/lsattr命令' },
        { text: 'mc命令', link: '/toolSoftware/Linux/mc命令' },
        { text: 'more命令', link: '/toolSoftware/Linux/more命令' },
        { text: 'mv命令', link: '/toolSoftware/Linux/mv命令' },
        { text: 'netstat命令', link: '/toolSoftware/Linux/netstat命令' },
        { text: 'od命令', link: '/toolSoftware/Linux/od命令' },
        { text: 'paste命令', link: '/toolSoftware/Linux/paste命令' },
        { text: 'patch命令', link: '/toolSoftware/Linux/patch命令' },
        { text: 'pico命令', link: '/toolSoftware/Linux/pico命令' },
        { text: 'ps命令', link: '/toolSoftware/Linux/ps命令' },
        { text: 'rcp命令', link: '/toolSoftware/Linux/rcp命令' },
        { text: 'read命令', link: '/toolSoftware/Linux/read命令' },
        { text: 'rm命令', link: '/toolSoftware/Linux/rm命令' },
        { text: 'scp命令', link: '/toolSoftware/Linux/scp命令' },
        { text: 'sed命令', link: '/toolSoftware/Linux/sed命令' },
        { text: 'sort命令', link: '/toolSoftware/Linux/sort命令' },
        { text: 'split命令', link: '/toolSoftware/Linux/split命令' },
        { text: 'systemctl命令', link: '/toolSoftware/Linux/systemctl命令' },
        { text: 'tee命令', link: '/toolSoftware/Linux/tee命令' },
        { text: 'tmpwatch命令', link: '/toolSoftware/Linux/tmpwatch命令' },
        { text: 'top命令', link: '/toolSoftware/Linux/top命令' },
        { text: 'touch命令', link: '/toolSoftware/Linux/touch命令' },
        { text: 'tr命令', link: '/toolSoftware/Linux/tr命令' },
        { text: 'traceroute命令', link: '/toolSoftware/Linux/traceroute命令' },
        { text: 'umask命令', link: '/toolSoftware/Linux/umask命令' },
        { text: 'updatedb命令', link: '/toolSoftware/Linux/updatedb命令' },
        { text: 'whereis命令', link: '/toolSoftware/Linux/whereis命令' },
        { text: 'which命令', link: '/toolSoftware/Linux/which命令' },
      ],
    },
  ]
}
